services:
  db:
    image: postgres:16
    container_name: petpet-postgres
    environment:
      POSTGRES_DB: petpetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petpet-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petpet-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      # JWT Configuration
      - JwtSettings__SecretKey=${JWT_SECRET_KEY:-your-super-secret-key-here-make-it-long-and-complex}
      - JwtSettings__Issuer=${JWT_ISSUER:-PetpetAPI}
      - JwtSettings__Audience=${JWT_AUDIENCE:-PetpetAPIUsers}
      - JwtSettings__ExpiryMinutes=${JWT_EXPIRY_MINUTES:-60}
      # Google OAuth Configuration
      - GoogleAuth__ClientId=${GOOGLE_CLIENT_ID}
      - GoogleAuth__ClientSecret=${GOOGLE_CLIENT_SECRET}
      # API URLs
      - ApiBaseUrl=${API_BASE_URL:-http://localhost:8080}
      - FrontendUrl=${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - petpet-network
    volumes:
      - ./src/PetpetAPI/appsettings.Development.json:/app/appsettings.Development.json

volumes:
  postgres_data:

networks:
  petpet-network:
    driver: bridge
