// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetpetAPI.Data;

#nullable disable

namespace PetpetAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250531000001_AddOAuthFieldsToUser")]
    partial class AddOAuthFieldsToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a simplified designer file - the actual file would contain all entity configurations
            // The key addition is the OAuth fields in the User entity
        }
    }
}
